[package]
name = "archive-cli"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
structopt = "0.3.8"
serde_json = "1.0"
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.125", features = ["derive"] }
futures = { version = "0.3.9", features = ["compat"] }
jsonrpc-core = "15.1.0"

archive-primitives = { path = "../primitives" }
archive-runtime = { path = "../runtime" }
archive-executor = { path = "../executor" }

ac-service = { default-features = false, path = "../../../client/service" }
ac-traits = { path = "../../../client/core/traits" }
ac-executor = { path = "../../../client/core/executor" }
ac-notifier = { path = "../../../client/core/notifier" }
ac-common = { path = "../../../client/common" }

sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sp-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-consensus-manual-seal = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-chain-spec = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

sp-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
sc-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

grandpa-primitives = { version = "3.0.0", package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", rev="22193e0" }
grandpa = { version = "0.9.0", package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", rev="22193e0" }
pallet-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", rev="22193e0" }
